sepolicy-legacy-um: init_shell.te: Adjust typealias for vendor_qti_init_shell
Partial revert of: Ia8953ed61bb1b87d01b17d02fc7e4bf4b86e66eb

* The typealias completely breaks mka dist complaining about usage being in correct partition namespaces.

error: https://hastebin.com/nujefemidi.sql

Signed-off-by: Andrew Hexen <SyberHexen@gmail.com>
Change-Id: I1bc64eb0603fa608f713d1e3b1c24de92794ea3b